application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "yadea"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "wj572305426@gmail.com"
  authorization_token: "e1c5eee6-0ead-4333-9b7e-f452c8ef0209"
  timeout_milliseconds: 10000
