application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "localhost"
  port: 5432
  username: "yadea"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "wangjin@yadea.com.cn"
  authorization_token: "e1c5eee6-0ead-4333-9b7e-f452c8ef0209"
  timeout_milliseconds: 10000
